teleop_twist_joy_node:
  ros__parameters:
    require_enable_button: false
    axis_linear:
      x: 1
    axis_angular:
      yaw: 3
    scale_linear:
      x: 1.0
    scale_angular:
      yaw: 1.0


joy_node:
  ros__parameters:
    deadzone: 0.1
    sticky_buttons: false
    autorepeat_rate: 50.0


evdev_joy_node:
  ros__parameters:
    deadzone: 0.1
    device_path: /dev/input/event0
    frame_id: ''
    joy_topic: joy
    reconnect_seconds: 3.0
    use_sim_time: false